"""Curated bilingual content for the complete Twin Peaks Season 2 atlas."""

from __future__ import annotations


def character(
    key,
    name,
    english,
    source_names,
    gender,
    plotline,
    group,
    importance,
    notes,
    node_type="person",
):
    aliases = [english] if isinstance(english, str) else list(english)
    return {
        "key": key,
        "name": name,
        "aliases": aliases,
        "sourceNames": source_names,
        "gender": gender,
        "plotline": plotline,
        "group": group,
        "importance": importance,
        "notes": notes,
        "nodeType": node_type,
    }


def event(episode, key, title, plotline, summary, participants):
    return {
        "episode": episode,
        "key": key,
        "title": title,
        "plotline": plotline,
        "summary": summary,
        "participants": participants,
    }


def relation(source, target, label, episodes, notes, directed=False, hidden=False):
    return {
        "source": source,
        "target": target,
        "label": label,
        "episodes": episodes,
        "notes": notes,
        "directed": directed,
        "hidden": hidden,
    }


def family(
    key,
    kind,
    subtype,
    participants,
    label,
    status="unknown",
    certainty="confirmed",
    episodes=None,
    notes="",
    context=None,
):
    return {
        "key": key,
        "kind": kind,
        "subtype": subtype,
        "participants": participants,
        "label": label,
        "status": status,
        "certainty": certainty,
        "episodes": episodes or [],
        "notes": notes,
        "context": context,
    }


CATEGORIES = [
    {
        "id": "node-type",
        "name": "节点类型",
        "visible": True,
        "tags": [
            {"id": "person", "name": "人物", "color": "#d7b06f"},
            {"id": "event", "name": "逐集事件", "color": "#d96262"},
            {"id": "entity", "name": "超自然实体", "color": "#9c7bd6"},
        ],
    },
    {
        "id": "plotline",
        "name": "剧情线",
        "visible": True,
        "tags": [
            {"id": "laura-case", "name": "劳拉案", "color": "#e45d67"},
            {"id": "lodge", "name": "黑白小屋", "color": "#9670d8"},
            {"id": "earle-fbi", "name": "厄尔 / FBI", "color": "#5d95cf"},
            {"id": "packard", "name": "帕卡德 / 幽灵木", "color": "#55a5a2"},
            {"id": "horne", "name": "霍恩 / 独眼杰克", "color": "#dc873e"},
            {"id": "teen", "name": "唐娜 / 哈罗德 / 詹姆斯", "color": "#bf78a8"},
            {"id": "johnson", "name": "雪莉 / 鲍比 / 利奥", "color": "#7eaa61"},
            {"id": "diner", "name": "双 R / 艾德 / 娜丁", "color": "#d4b23e"},
            {"id": "town", "name": "警局 / 镇民", "color": "#84919a"},
            {"id": "pageant", "name": "选美 / 唐娜身世", "color": "#cf8cae"},
            {"id": "marsh", "name": "詹姆斯 / 伊芙琳", "color": "#a98265"},
        ],
    },
    {
        "id": "group",
        "name": "身份 / 家族",
        "visible": False,
        "tags": [
            {"id": "fbi", "name": "FBI / DEA", "color": "#5d95cf"},
            {"id": "sheriff", "name": "警长办公室", "color": "#89959e"},
            {"id": "palmer", "name": "帕尔默家", "color": "#e45d67"},
            {"id": "hayward", "name": "海沃德家", "color": "#bf78a8"},
            {"id": "horne-family", "name": "霍恩家", "color": "#dc873e"},
            {"id": "briggs", "name": "布里格斯家 / 空军", "color": "#6b8fbd"},
            {"id": "hurley", "name": "赫利家", "color": "#8b79b8"},
            {"id": "diner-family", "name": "双 R / 詹宁斯", "color": "#d4b23e"},
            {"id": "johnson-family", "name": "约翰逊家", "color": "#7eaa61"},
            {"id": "packard-family", "name": "帕卡德 / 马特尔", "color": "#55a5a2"},
            {"id": "renault", "name": "雷诺 / 独眼杰克", "color": "#b65454"},
            {"id": "lodge-entity", "name": "小屋实体", "color": "#9670d8"},
            {"id": "townspeople", "name": "镇民 / 其他", "color": "#9da5a8"},
        ],
    },
    {
        "id": "importance",
        "name": "叙事重要度",
        "visible": True,
        "tags": [
            {"id": "core", "name": "核心", "color": "#f2d06b"},
            {"id": "major", "name": "主要", "color": "#9bc58b"},
            {"id": "supporting", "name": "支撑", "color": "#8db6d8"},
            {"id": "context", "name": "背景", "color": "#6e747b"},
        ],
    },
]


CHARACTERS = [
    character("cooper", "戴尔·库珀", "Dale Cooper", ["Dale Cooper"], "male", "earle-fbi", "fbi", "core", "FBI 特工；第二季从中枪复原、侦破劳拉案，一路走到温德姆·厄尔与黑色小屋。"),
    character("truman", "哈里·S·杜鲁门", "Harry S. Truman", ["Harry S. Truman"], "male", "town", "sheriff", "core", "双峰镇警长，库珀最稳定的本地搭档，也是乔西线的情感核心。"),
    character("albert", "阿尔伯特·罗森菲尔德", "Albert Rosenfield", ["Albert Rosenfield"], "male", "earle-fbi", "fbi", "major", "FBI 法医专家，提供劳拉案、库珀枪击案、乔西与厄尔案的关键证据。"),
    character("gordon", "戈登·科尔", "Gordon Cole", ["Gordon Cole"], "male", "earle-fbi", "fbi", "major", "库珀的 FBI 上司，带来厄尔、蓝皮书计划与复职信息。"),
    character("hawk", "汤米“鹰”希尔", ['Tommy "Hawk" Hill', "Hawk"], ["Hawk"], "male", "town", "sheriff", "major", "警长办公室副警长，追踪能力出众，并向库珀解释黑白小屋传统。"),
    character("andy", "安迪·布伦南", "Andy Brennan", ["Andy Brennan"], "male", "town", "sheriff", "major", "副警长；参与劳拉案、尼基支线和猫头鹰洞符号破解，并牵涉露西孩子的父亲之争。"),
    character("lucy", "露西·莫兰", ["Lucy Moran", "Lucy Brennan"], ["Lucy Brennan"], "female", "town", "sheriff", "major", "警局接线员；在安迪与迪克之间处理感情和未出生孩子的父亲问题。"),
    character("roger", "罗杰·哈迪", "Roger Hardy", ["Roger Hardy"], "male", "earle-fbi", "fbi", "supporting", "FBI 区域负责人，因独眼杰克突袭案暂停库珀职务。"),
    character("denise", "丹尼斯·布莱森", "Denise Bryson", ["Denise Bryson"], "female", "earle-fbi", "fbi", "major", "DEA 特工和库珀旧友，调查失踪可卡因并协助诱捕让·雷诺。"),
    character("preston", "普雷斯顿·金", "Preston King", ["Preston King"], "male", "earle-fbi", "townspeople", "supporting", "卷入陷害库珀计划的加拿大骑警。"),
    character("garland", "加兰·布里格斯少校", "Garland Briggs", ["Garland Briggs"], "male", "lodge", "briggs", "core", "美国空军少校；蓝皮书计划、白色小屋、猫头鹰洞和厄尔目标之间的关键连接。"),
    character("betty", "贝蒂·布里格斯", "Betty Briggs", ["Betty Briggs"], "female", "town", "briggs", "supporting", "加兰的妻子、鲍比的母亲，在少校失踪和归来期间维系家庭。"),
    character("bobby", "鲍比·布里格斯", "Bobby Briggs", ["Bobby Briggs"], "male", "johnson", "briggs", "major", "雪莉的情人、劳拉的前男友；从利奥保险骗局转向为本·霍恩办事。"),
    character("windom", "温德姆·厄尔", "Windom Earle", ["Windom Earle"], "male", "earle-fbi", "fbi", "core", "库珀的前搭档和主要反派，以杀人棋局复仇，并试图夺取黑色小屋力量。"),
    character("annie", "安妮·布莱克本", "Annie Blackburn", ["Annie Blackburn"], "female", "pageant", "diner-family", "core", "诺玛同母异父的妹妹；与库珀相爱，赢得双峰小姐后被厄尔绑入小屋。"),
    character("caroline", "卡罗琳·厄尔", ["Caroline Earle", "Caroline Powell"], ["Caroline Earle"], "female", "earle-fbi", "fbi", "major", "厄尔的妻子、库珀未能保护的旧爱；她的死亡解释两位特工的宿怨。"),
    character("laura", "劳拉·帕尔默", "Laura Palmer", ["Laura Palmer"], "female", "laura-case", "palmer", "core", "已被杀害的少女；日记、幻象和真凶揭示继续支配第二季前半段，并在终集小屋中出现。"),
    character("leland", "利兰·帕尔默", "Leland Palmer", ["Leland Palmer"], "male", "laura-case", "palmer", "core", "劳拉的父亲和 BOB 的宿主，杀害劳拉与麦蒂，真相揭露后死于拘押中。"),
    character("sarah", "莎拉·帕尔默", "Sarah Palmer", ["Sarah Palmer"], "female", "laura-case", "palmer", "major", "劳拉的母亲，持续遭受幻象与家庭灾难，终集成为小屋信息的传声者。"),
    character("maddy", "麦蒂·弗格森", "Maddy Ferguson", ["Maddy Ferguson"], "female", "laura-case", "palmer", "core", "劳拉的表姐；帮助调查日记，随后被利兰／BOB 杀害。"),
    character("bob", "BOB", "BOB", ["BOB"], "male", "lodge", "lodge-entity", "core", "寄宿并利用利兰的恶意实体；连接两起谋杀、乔西之死和库珀终局。", "entity"),
    character("mike", "MIKE／菲利普·杰拉德", ["MIKE", "Phillip Gerard", "Phillip Michael Gerard"], ["Mike", "Phillip Michael Gerard"], "male", "lodge", "lodge-entity", "core", "独臂鞋商杰拉德体内的实体 MIKE，为库珀指出 BOB 的存在与藏身处。", "entity"),
    character("giant", "巨人", "The Giant", ["Giant"], "male", "lodge", "lodge-entity", "core", "在幻象中向库珀提供三条线索，并在关键时刻发出警告。", "entity"),
    character("arm", "另一个地方的人", ["The Man from Another Place", "The Arm"], ["The arm"], "male", "lodge", "lodge-entity", "major", "红房间／小屋中的矮个身影，参与真凶揭示与终集试炼。", "entity"),
    character("waiter", "老侍者", "The Waiter", ["Waiter"], "male", "lodge", "lodge-entity", "supporting", "大北方酒店的老侍者；形象与巨人互相呼应，并在麦蒂遇害与终集中出现。", "entity"),
    character("ronette", "罗内特·普拉斯基", "Ronette Pulaski", ["Ronette Pulaski"], "female", "laura-case", "townspeople", "major", "劳拉遇害当晚的幸存者；从昏迷中醒来并认出 BOB。"),
    character("donna", "唐娜·海沃德", "Donna Hayward", ["Donna Hayward"], "female", "teen", "hayward", "core", "劳拉的好友；追查送餐路线和秘密日记，后期又追索自己的身世。"),
    character("will", "威尔·海沃德医生", "Will Hayward", ["Will Hayward"], "male", "town", "hayward", "major", "镇医师、唐娜的养父；参与多起验伤，并在身世真相爆发时攻击本。"),
    character("eileen", "艾琳·海沃德", "Eileen Hayward", ["Eileen Hayward"], "female", "pageant", "hayward", "major", "唐娜的母亲；与本的旧情使唐娜的亲生父亲问题在季末浮出。"),
    character("gersten", "格斯滕·海沃德", "Gersten Hayward", ["Gersten Hayward"], "female", "town", "hayward", "context", "海沃德家的小女儿，在第二季首集家庭聚会中演奏钢琴。"),
    character("harriet", "哈丽特·海沃德", "Harriet Hayward", ["Harriet Hayward"], "female", "town", "hayward", "context", "海沃德家的女儿，在家庭聚会上朗读写给劳拉的诗。"),
    character("james", "詹姆斯·赫利", "James Hurley", ["James Hurley"], "male", "teen", "hurley", "major", "劳拉与唐娜的恋情人物；离镇后卷入伊芙琳·马什的谋杀陷害。"),
    character("ed", "大艾德·赫利", ["Big Ed Hurley", "Ed Hurley"], ["Ed Hurley"], "male", "diner", "hurley", "major", "娜丁的丈夫、诺玛的长期爱人，也照看侄子詹姆斯。"),
    character("nadine", "娜丁·赫利", "Nadine Hurley", ["Nadine Hurley"], "female", "diner", "hurley", "major", "自杀未遂后认为自己是高中生并获得异常力量，终集头部受伤后恢复真实年龄认知。"),
    character("mike_nelson", "迈克·尼尔森", "Mike Nelson", ["Mike Nelson"], "male", "diner", "townspeople", "supporting", "高中生；在娜丁失忆期间与她交往，并在终集面对她恢复记忆。"),
    character("harold", "哈罗德·史密斯", "Harold Smith", ["Harold Smith"], "male", "teen", "townspeople", "major", "患广场恐惧的送餐对象，保管劳拉秘密日记；与唐娜关系破裂后自杀。"),
    character("jacoby", "劳伦斯·雅各比医生", "Lawrence Jacoby", ["Lawrence Jacoby"], "male", "teen", "townspeople", "major", "劳拉的心理医生；辨认利兰、照护娜丁，并帮助本摆脱内战妄想。"),
    character("log_lady", "木头女士玛格丽特", ["Margaret Lanterman", "The Log Lady"], ["Margaret Lanterman"], "female", "lodge", "townspeople", "major", "以直觉与木头传递线索；其失踪伤痕连接布里格斯经历和猫头鹰洞。"),
    character("mrs_tremond", "特里蒙德夫人", ["Mrs. Tremond", "Mrs. Chalfont"], ["Mrs. Tremond"], "female", "lodge", "lodge-entity", "supporting", "唐娜送餐时遇到的神秘老妇，奶油玉米异象和孙子引出日记页线索。", "entity"),
    character("pierre", "皮埃尔·特里蒙德", "Pierre Tremond", ["Pierre Tremond"], "male", "lodge", "lodge-entity", "supporting", "特里蒙德夫人的孙子，以魔术和法语短句指向哈罗德与秘密日记。", "entity"),
    character("mrs_tremond_second", "第二位“特里蒙德夫人”", "Second Mrs. Tremond", ["Mrs. Tremond (second)"], "female", "laura-case", "townspeople", "context", "声称自己才住在该地址，并把劳拉日记残页交给唐娜的女人。"),
    character("audrey", "奥黛丽·霍恩", "Audrey Horne", ["Audrey Horne"], "female", "horne", "horne-family", "core", "本的女儿；从独眼杰克获救后参与本的复原、幽灵木抗议、惠勒恋情与选美线。"),
    character("ben", "本杰明·霍恩", "Benjamin Horne", ["Benjamin Horne"], "male", "horne", "horne-family", "core", "大北方酒店与幽灵木计划的操盘者；曾被误捕，后陷入内战妄想，并承认可能是唐娜生父。"),
    character("jerry", "杰里·霍恩", "Jerry Horne", ["Jerry Horne"], "male", "horne", "horne-family", "supporting", "本的弟弟、律师和商业同谋，参与独眼杰克、辩护与内战妄想。"),
    character("sylvia", "西尔维娅·霍恩", "Sylvia Horne", ["Sylvia Horne"], "female", "horne", "horne-family", "context", "本的妻子、奥黛丽与约翰尼的母亲。"),
    character("johnny", "约翰尼·霍恩", "Johnny Horne", ["Johnny Horne"], "male", "horne", "horne-family", "context", "本与西尔维娅的儿子；在本的内战妄想和家庭场景中出现。"),
    character("wheeler", "约翰·贾斯蒂斯·惠勒", "John Justice Wheeler", ["John Justice Wheeler"], "male", "horne", "townspeople", "major", "本请来对付凯瑟琳的商业伙伴，与奥黛丽发展短暂恋情。"),
    character("jean", "让·雷诺", "Jean Renault", ["Jean Renault"], "male", "horne", "renault", "major", "雅克与伯纳德的兄弟；绑架奥黛丽、陷害库珀并在死狗农场劫持他。"),
    character("blackie", "布莱姬·奥赖利", "Blackie O'Reilly", ["Blackie O'Reilly"], "female", "horne", "renault", "supporting", "独眼杰克的管理者，识破并囚禁奥黛丽，营救行动中被杀。"),
    character("nancy", "南希·奥赖利", "Nancy O'Reilly", ["Nancy O'Reilly"], "female", "horne", "renault", "context", "布莱姬的妹妹，参与奥黛丽绑架与独眼杰克行动。"),
    character("emory", "埃默里·巴蒂斯", "Emory Battis", ["Emory Battis"], "male", "horne", "renault", "context", "霍恩百货香水柜台经理，为独眼杰克挑选年轻女性。"),
    character("shelly", "雪莉·约翰逊", ["Shelly Johnson", "Shelly Briggs"], ["Shelly Briggs"], "female", "johnson", "johnson-family", "core", "利奥的妻子、鲍比的情人；护理失能的利奥并多次遭其攻击。"),
    character("leo", "利奥·约翰逊", "Leo Johnson", ["Leo Johnson"], "male", "johnson", "johnson-family", "major", "暴力卡车司机；从枪击与昏迷中醒来后被厄尔控制。"),
    character("hank", "汉克·詹宁斯", "Hank Jennings", ["Hank Jennings"], "male", "johnson", "diner-family", "major", "诺玛分居的罪犯丈夫，卷入利奥枪击、雷诺交易和乔西阴谋。"),
    character("norma", "诺玛·詹宁斯", "Norma Jennings", ["Norma Jennings"], "female", "diner", "diner-family", "major", "双 R 餐厅老板、艾德的长期爱人，也是安妮的姐姐。"),
    character("vivian", "维维安·奈尔斯", ["Vivian Smythe Niles", "M.T. Wentz"], ["Vivian Smythe", "Vivian Smythe Niles"], "female", "diner", "diner-family", "supporting", "诺玛的母亲，化名美食评论家 M.T. Wentz 给女儿餐厅差评。"),
    character("ernie", "厄尼·奈尔斯", "Ernie Niles", ["Ernie Niles"], "male", "earle-fbi", "diner-family", "supporting", "维维安的丈夫、汉克旧狱友，被让利用并被丹尼斯迫使协助诱捕。"),
    character("dick", "迪克·特雷梅恩", "Dick Tremayne", ["Dick Tremayne"], "male", "town", "townspeople", "supporting", "露西的另一位情人和孩子父亲候选；与安迪共同照看尼基，并参与幽灵木活动。"),
    character("nicky", "尼基·尼德尔曼", "Nicky Needleman", ["Nicky Needleman"], "male", "town", "townspeople", "context", "被安迪和迪克共同照看的孤儿；一连串事故令迪克误以为他带来厄运。"),
    character("josie", "乔西·帕卡德", "Josie Packard", ["Josie Packard"], "female", "packard", "packard-family", "core", "帕卡德锯木厂寡妇；实际枪击库珀，受安德鲁与埃克哈特操控，最终神秘死亡。"),
    character("catherine", "凯瑟琳·马特尔", "Catherine Martell", ["Catherine Martell"], "female", "packard", "packard-family", "core", "火灾幸存后化装成东村先生，夺回幽灵木利益并操控乔西。"),
    character("pete", "皮特·马特尔", "Pete Martell", ["Pete Martell"], "male", "packard", "packard-family", "major", "凯瑟琳的丈夫；擅长国际象棋，协助库珀拖延厄尔，也参与开启埃克哈特盒子。"),
    character("andrew", "安德鲁·帕卡德", "Andrew Packard", ["Andrew Packard"], "male", "packard", "packard-family", "major", "乔西被认为已死的丈夫、凯瑟琳兄弟；与凯瑟琳合谋后追索埃克哈特遗产。"),
    character("eckhardt", "托马斯·埃克哈特", "Thomas Eckhardt", ["Thomas Eckhardt"], "male", "packard", "packard-family", "major", "香港商人、乔西旧情人与控制者；来镇逼迫乔西，最终被她射杀。"),
    character("jonathan", "乔纳森·熊谷", "Jonathan Kumagai", ["Jonathan Kumagai"], "male", "packard", "packard-family", "supporting", "埃克哈特的执行者，监视并威胁乔西与汉克，后被乔西杀害。"),
    character("jones", "琼斯", "Jones", ["Jones"], "female", "packard", "packard-family", "supporting", "埃克哈特的助手，将谜盒送给凯瑟琳并试图杀死杜鲁门。"),
    character("dwayne", "德韦恩·米尔福德", "Dwayne Milford", ["Dwayne Milford"], "male", "town", "townspeople", "supporting", "双峰镇长，与弟弟道吉争执；后来迷恋拉娜并同意操纵选美。"),
    character("dougie", "道吉·米尔福德", "Dougie Milford", ["Dougie Milford"], "male", "town", "townspeople", "supporting", "报社老板、德韦恩的兄弟；迎娶拉娜后死于心脏病。"),
    character("lana", "拉娜·巴丁·米尔福德", "Lana Budding Milford", ["Lana Budding Milford"], "female", "pageant", "townspeople", "supporting", "道吉的年轻妻子，令镇上男性迷恋，并试图操纵双峰小姐选举。"),
    character("evelyn", "伊芙琳·马什", "Evelyn Marsh", ["Evelyn Marsh"], "female", "marsh", "townspeople", "major", "雇詹姆斯修车并与他发生关系，随后和马尔科姆设计把丈夫之死栽赃给詹姆斯。"),
    character("malcolm", "马尔科姆·斯隆", "Malcolm Sloan", ["Malcolm Sloan"], "male", "marsh", "townspeople", "supporting", "伊芙琳的情人和共犯，冒充其兄长并试图杀死詹姆斯。"),
    character("jeffrey", "杰弗里·马什", "Jeffrey Marsh", ["Jeffrey Marsh"], "male", "marsh", "townspeople", "supporting", "伊芙琳的丈夫，其死亡成为陷害詹姆斯的核心。"),
    character("judge", "克林顿·斯特恩伍德法官", "Judge Clinton Sternwood", ["Clinton Sternwood"], "male", "town", "townspeople", "context", "主持利兰保释与利奥受审能力听证，并提醒库珀留意树林。"),
    character("lodwick", "达里尔·洛德威克", "Daryl Lodwick", ["Daryl Lodwick"], "male", "town", "townspeople", "context", "地方检察官，参与利兰和利奥的法庭程序。"),
    character("jack_racine", "杰克·拉辛", "Jack Racine", ["Jack Racine"], "male", "town", "townspeople", "context", "利奥的律师，在听证中以脑活动图主张他没有受审能力。"),
    character("brunstons", "布伦斯顿夫妇", "Mr. and Mrs. Brunston", ["Brunstons"], None, "laura-case", "townspeople", "context", "住在利兰所指罗伯逊旧址的退休教师，否认认识 BOB 或罗伯逊。"),
    character("buck", "巴克·温盖特教练", "Buck Wingate", ["Buck Wingate"], "male", "diner", "townspeople", "context", "双峰高中摔跤教练，发现娜丁的异常力量并招她入队。"),
    character("judy_swain", "朱迪·斯温", "Judy Swain", ["Judy Swain"], "female", "town", "townspeople", "context", "负责尼基个案的社工，向露西、安迪和迪克解释他的创伤经历。"),
    character("colonel_reilly", "莱利上校", ["Colonel Reilly", "Calvin Reilly"], ["Calvin Reilly"], "male", "lodge", "briggs", "supporting", "布里格斯少校的上级，确认树林信号和少校失踪涉及国家安全。"),
    character("erik", "埃里克·鲍威尔", "Erik Powell", ["Erik Powell"], "male", "earle-fbi", "townspeople", "context", "厄尔杀人棋局中的早期受害者，尸体被放在警长办公室指向棋盘。"),
    character("rusty", "拉斯蒂·托马斯基", "Rusty Tomasky", ["Rusty Tomasky"], "male", "earle-fbi", "townspeople", "supporting", "被厄尔绑架并装入巨大棋子杀害的巡演音乐家。"),
    character("tim_pinkle", "蒂姆·平克尔", "Tim Pinkle", ["Tim Pinkle"], "male", "pageant", "townspeople", "context", "镇上活动主持人，参与幽灵木时装秀和双峰小姐选美。"),
    character("randy", "兰迪·圣克罗伊", "Randy St. Croix", ["Randy St. Croix"], "male", "horne", "townspeople", "context", "惠勒的助手和飞行员，负责其私人飞机行程。"),
    character("eolani", "伊奥拉妮·雅各比", "Eolani Jacoby", ["Eolani Jacoby"], "female", "town", "townspeople", "context", "雅各比医生的妻子，在他康复期间出现。"),
    character("brock", "布罗克·法明顿", "Brock Farmington", ["Brock Farmington"], "male", "pageant", "townspeople", "context", "双峰小姐活动中的镇民和舞台参与者。"),
    character("jacques", "雅克·雷诺", "Jacques Renault", ["Jacques Renault"], "male", "laura-case", "renault", "supporting", "第一季末被捕后遭利兰窒息；其死亡、家族复仇和劳拉案证据继续推动第二季。"),
    character("dell", "戴尔·米布勒", "Dell Mibbler", ["Dell Mibbler"], "male", "packard", "townspeople", "context", "双峰储蓄贷款银行老经理，为奥黛丽送水并带安德鲁、皮特找到致命保险箱。"),
    character("pale_horse", "白马", "Pale Horse", ["Pale horse"], None, "lodge", "lodge-entity", "supporting", "麦蒂遇害前莎拉看见的白马异象，作为昏迷、死亡与小屋力量的视觉预兆。", "entity"),
    character("cooper_double", "库珀的分身", "Dale Cooper's doppelganger", ["Dale Cooper (doppelganger)"], "male", "lodge", "lodge-entity", "core", "黑色小屋中追逐库珀并在终局回到现实的邪恶分身。", "entity"),
    character("laura_double", "劳拉的分身", "Laura Palmer's doppelganger", ["Laura Palmer (doppelganger)"], "female", "lodge", "lodge-entity", "supporting", "终集红房间中劳拉形象的凶恶分身。", "entity"),
    character("leland_double", "利兰的分身", "Leland Palmer's doppelganger", ["Leland Palmer (doppelganger)"], "male", "lodge", "lodge-entity", "supporting", "终集黑色小屋中出现的利兰分身。", "entity"),
    character("arm_double", "另一个地方的人的分身", "The Arm's doppelganger", ["The arm (doppelganger)"], "male", "lodge", "lodge-entity", "supporting", "终集红房间中另一个地方的人的分身。", "entity"),
    character("caroline_double", "卡罗琳的分身", "Caroline Earle's doppelganger", ["Caroline Earle (doppelganger)"], "female", "lodge", "lodge-entity", "supporting", "终集小屋中以卡罗琳外形出现并与安妮形象互换的欺骗性分身。", "entity"),
]


EPISODE_GUIDE = [
    {"episode": 1, "title": "愿巨人与君同在", "englishTitle": "May the Giant Be with You", "airDate": "1990-09-30", "summary": "库珀从枪击中生还并得到巨人线索；锯木厂火灾、劳拉案第三人和奥黛丽卧底同时进入新阶段。"},
    {"episode": 2, "title": "昏迷", "englishTitle": "Coma", "airDate": "1990-10-06", "summary": "罗内特认出 BOB，布里格斯转交猫头鹰信息；唐娜沿送餐路线调查，奥黛丽被识破囚禁。"},
    {"episode": 3, "title": "镜子背后的男人", "englishTitle": "The Man Behind the Glass", "airDate": "1990-10-13", "summary": "指甲字母与罗伯逊线索推进真凶调查；唐娜发现秘密日记，让·雷诺把奥黛丽变成复仇诱饵。"},
    {"episode": 4, "title": "劳拉的秘密日记", "englishTitle": "Laura's Secret Diary", "airDate": "1990-10-20", "summary": "利兰承认杀死雅克；哈罗德拒交日记，让向本勒索；乔西回镇并遭乔纳森威胁。"},
    {"episode": 5, "title": "兰花的诅咒", "englishTitle": "The Orchid's Curse", "airDate": "1990-10-27", "summary": "库珀与杜鲁门突袭独眼杰克救出奥黛丽；唐娜和麦蒂偷日记失败，娜丁以高中生心态醒来。"},
    {"episode": 6, "title": "恶魔", "englishTitle": "Demons", "airDate": "1990-11-03", "summary": "杰拉德体内的 MIKE 说出 BOB 藏身处；戈登带来枪击证据和厄尔棋步，奥黛丽回到父亲身边。"},
    {"episode": 7, "title": "孤独的灵魂", "englishTitle": "Lonely Souls", "airDate": "1990-11-10", "summary": "哈罗德死亡、日记被复原，本因劳拉案被捕；巨人警告之际，利兰／BOB 杀害麦蒂。"},
    {"episode": 8, "title": "与死去的女孩兜风", "englishTitle": "Drive with a Dead Girl", "airDate": "1990-11-17", "summary": "利兰携带麦蒂尸体穿城而过，本仍是错误嫌疑人；东村身份与利奥录音改变幽灵木利益。"},
    {"episode": 9, "title": "任意法则", "englishTitle": "Arbitrary Law", "airDate": "1990-12-01", "summary": "劳拉日记残页与巨人提示让库珀想起梦中真相；利兰被捕，BOB 离体，利兰死去。"},
    {"episode": 10, "title": "兄弟之争", "englishTitle": "Dispute Between Brothers", "airDate": "1990-12-08", "summary": "劳拉案收束后库珀被停职；米尔福德婚姻闹剧、雷诺毒品阴谋和布里格斯失踪开启后半季。"},
    {"episode": 11, "title": "化装舞会", "englishTitle": "Masked Ball", "airDate": "1990-12-15", "summary": "丹尼斯抵达调查库珀；鹰解释黑白小屋，詹姆斯遇见伊芙琳，安德鲁仍活着的事实揭开。"},
    {"episode": 12, "title": "黑寡妇", "englishTitle": "The Black Widow", "airDate": "1991-01-12", "summary": "库珀筹划死狗农场诱捕；道吉猝死、娜丁加入摔跤队、布里格斯归来，乔西沦为凯瑟琳女佣。"},
    {"episode": 13, "title": "将死", "englishTitle": "Checkmate", "airDate": "1991-01-19", "summary": "雷诺反制诱捕但被击毙；利奥苏醒，厄尔以停电和棋局受害者正式进入双峰镇。"},
    {"episode": 14, "title": "双重攻势", "englishTitle": "Double Play", "airDate": "1991-02-02", "summary": "利奥袭击雪莉后逃入厄尔手中；库珀讲述卡罗琳之死，埃克哈特抵达，詹姆斯遭陷害。"},
    {"episode": 15, "title": "奴隶与主人", "englishTitle": "Slaves and Masters", "airDate": "1991-02-09", "summary": "厄尔奴役利奥并向三名女子送诗；皮特协助拖延棋局，伊芙琳反杀马尔科姆洗清詹姆斯。"},
    {"episode": 16, "title": "被判刑的女人", "englishTitle": "The Condemned Woman", "airDate": "1991-02-16", "summary": "证据确认乔西枪击库珀；她被迫面对埃克哈特，射杀对方后神秘死亡并留下 BOB 异象。"},
    {"episode": 17, "title": "创伤与伤痕", "englishTitle": "Wounds and Scars", "airDate": "1991-03-28", "summary": "杜鲁门沉溺于丧失乔西；安妮来到双 R，厄尔继续伪装渗透，幽灵木时装秀失控。"},
    {"episode": 18, "title": "爱之翼", "englishTitle": "On the Wings of Love", "airDate": "1991-04-04", "summary": "戈登恢复库珀职务并连接厄尔与蓝皮书；安妮认出猫头鹰洞符号，厄尔锁定双峰小姐。"},
    {"episode": 19, "title": "关系变奏", "englishTitle": "Variations on Relations", "airDate": "1991-04-11", "summary": "厄尔讲述黑色小屋并杀害拉斯蒂；库珀与安妮敞开心扉，谜盒和选美操纵同时推进。"},
    {"episode": 20, "title": "通往黑色小屋之路", "englishTitle": "The Path to the Black Lodge", "airDate": "1991-04-18", "summary": "库珀识破厄尔真正目标；厄尔绑架布里格斯得到行星会合线索，猫头鹰洞图成为小屋地图。"},
    {"episode": 21, "title": "双峰小姐", "englishTitle": "Miss Twin Peaks", "airDate": "1991-06-10", "summary": "爱与恐惧、木星与土星的提示汇合；安妮赢得选美后被伪装的厄尔绑走。"},
    {"episode": 22, "title": "超越生死", "englishTitle": "Beyond Life and Death", "airDate": "1991-06-10", "summary": "库珀追入黑色小屋，现实中家族与幽灵木冲突爆炸；库珀分身返回，留下 BOB 附身悬念。"},
]


EVENTS = [
    event(1, "cooper-shot", "库珀中枪与巨人三条线索", "lodge", "老侍者迟缓应对伤势，巨人在幻象中给出三条线索并取走库珀戒指。", [("cooper", "中枪后获得线索"), ("giant", "给出三条线索"), ("waiter", "送牛奶并呼应巨人"), ("andy", "电话求援"), ("truman", "赶到并送医"), ("albert", "调查枪击")]),
    event(1, "mill-aftermath", "锯木厂火灾余波", "packard", "雪莉和皮特获救，凯瑟琳失踪，乔西离镇，利奥在警戒中存活。", [("shelly", "从火场获救"), ("pete", "从火场获救"), ("catherine", "失踪"), ("josie", "离镇避嫌"), ("leo", "重伤存活")]),
    event(1, "third-man", "劳拉案锁定“第三个人”", "laura-case", "利奥在特雷莎遇害时另有不在场证明，雅各比回忆焦油味，罗内特重现 BOB 袭击。", [("cooper", "排除利奥和雅克"), ("truman", "继续调查"), ("leo", "获得关键不在场证明"), ("jacoby", "提供焦油气味线索"), ("ronette", "在昏迷中重现袭击"), ("bob", "出现在罗内特记忆中")]),
    event(1, "audrey-undercover", "奥黛丽在独眼杰克暴露于危险", "horne", "奥黛丽继续卧底并险些接待自己的父亲，布莱姬开始限制她的行动。", [("audrey", "卧底面临暴露"), ("ben", "不知情地接近女儿"), ("jerry", "打断房间会面"), ("blackie", "控制奥黛丽")]),
    event(1, "family-aftershocks", "医院与家庭余波", "diner", "布里格斯向鲍比讲述充满希望的梦；艾德回顾与娜丁、诺玛的三角关系。", [("garland", "向儿子分享愿景"), ("bobby", "被父亲的话触动"), ("ed", "讲述婚姻往事"), ("nadine", "昏迷住院"), ("norma", "照看雪莉并面对艾德")]),
    event(1, "hayward-supper", "海沃德家庭晚宴悼念劳拉", "laura-case", "格斯滕弹琴、哈丽特朗读写给劳拉的诗；利兰在帕尔默与海沃德两家面前情绪失控。", [("gersten", "演奏钢琴"), ("harriet", "朗读悼念诗"), ("will", "主持家庭聚会"), ("eileen", "接待帕尔默一家"), ("donna", "与家人悼念好友"), ("sarah", "被悼念触动"), ("leland", "唱歌并短暂倒地"), ("maddy", "参加聚会"), ("laura", "成为悼念对象")]),

    event(2, "earle-escape", "温德姆·厄尔逃离精神病院", "earle-fbi", "阿尔伯特警告库珀，他极度危险的前搭档温德姆·厄尔已经逃脱。", [("albert", "传达逃脱警报"), ("cooper", "得知旧敌回归"), ("windom", "逃离精神病院")]),
    event(2, "meals-on-wheels", "送餐路线与奶油玉米异象", "teen", "唐娜接替劳拉送餐，遇到特里蒙德祖孙并沿线接触哈罗德。", [("donna", "追查劳拉送餐路线"), ("mrs_tremond", "拒绝奶油玉米"), ("pierre", "让玉米瞬间转移"), ("harold", "进入唐娜调查范围"), ("laura", "旧送餐路线成为线索")]),
    event(2, "ronette-awakens", "罗内特醒来并认出 BOB", "laura-case", "罗内特从昏迷中醒来指认 BOB，利兰也把画像与童年中的罗伯逊联系起来。", [("ronette", "醒来并指认凶手形象"), ("bob", "被认出"), ("cooper", "获得幸存者确认"), ("leland", "认出童年中的罗伯逊")]),
    event(2, "owls-message", "“猫头鹰并非其表象”", "lodge", "布里格斯把深空监听收到的信息转交库珀；麦蒂同时看到 BOB 幻象。", [("garland", "传递监听信息"), ("cooper", "收到超自然警告"), ("maddy", "看见 BOB"), ("bob", "出现在幻象中")]),
    event(2, "leo-scam", "利奥伤残补助计划", "johnson", "鲍比劝雪莉把植物状态的利奥接回家，以伤残补助维持两人的生活。", [("bobby", "策划补助骗局"), ("shelly", "同意护理丈夫"), ("leo", "成为补助对象")]),
    event(2, "audrey-captured", "奥黛丽身份暴露并被囚禁", "horne", "布莱姬识破奥黛丽，给她注射毒品并把她拘禁在独眼杰克。", [("audrey", "身份暴露"), ("blackie", "下药并囚禁"), ("emory", "香水柜台链条被追查")]),
    event(2, "andy-paternity", "安迪得知自己不育", "town", "安迪的检查结果让他认为露西的孩子来自另一段关系。", [("andy", "收到不育结果"), ("lucy", "隐瞒迪克关系")]),

    event(3, "fingernail-letters", "指甲字母开始拼出罗伯逊", "laura-case", "罗内特指甲下的 B 与劳拉、特雷莎身上的字母形成连续模式。", [("cooper", "识别字母模式"), ("ronette", "提供 B 字线索"), ("laura", "R 字受害者"), ("bob", "罗伯逊名称被逼近")]),
    event(3, "secret-diary-found", "唐娜发现劳拉秘密日记", "teen", "唐娜认识哈罗德并发现他保管着劳拉的另一册日记。", [("donna", "接近哈罗德"), ("harold", "保管秘密日记"), ("laura", "把日记托付给哈罗德")]),
    event(3, "leland-identified", "雅各比在催眠中指认利兰", "laura-case", "利兰说出童年罗伯逊经历；雅各比辨认他是杀死雅克的人，杜鲁门将其逮捕。", [("leland", "交代童年线索并被捕"), ("jacoby", "在催眠中指认"), ("truman", "执行逮捕"), ("cooper", "连接罗伯逊名称"), ("jacques", "死亡被雅各比指向利兰")]),
    event(3, "renault-revenge", "让·雷诺把奥黛丽变成复仇诱饵", "horne", "让与奥赖利姐妹控制被下药的奥黛丽，计划引库珀进入独眼杰克。", [("jean", "策划报复库珀"), ("audrey", "被当作诱饵"), ("blackie", "看守人质"), ("nancy", "参与看守"), ("cooper", "成为复仇目标")]),
    event(3, "shelly-testimony", "雪莉拒绝指证利奥", "johnson", "雪莉为保住补助计划拒绝说明火灾经过，引起库珀怀疑。", [("shelly", "拒绝作证"), ("leo", "保持失能状态"), ("cooper", "怀疑补助骗局"), ("bobby", "维持计划")]),
    event(3, "teen-triangle", "唐娜察觉詹姆斯与麦蒂接近", "teen", "詹姆斯与麦蒂的吸引使唐娜感到被劳拉的影子再次排除在外。", [("donna", "感到嫉妒"), ("james", "接近麦蒂"), ("maddy", "与詹姆斯产生吸引"), ("laura", "记忆笼罩三人")]),

    event(4, "leland-confesses", "利兰承认杀死雅克", "laura-case", "利兰对窒息雅克认罪，地方司法开始处理他的保释。", [("leland", "承认杀人"), ("truman", "羁押嫌疑人"), ("judge", "准备听证"), ("lodwick", "参与起诉")]),
    event(4, "diary-refused", "哈罗德拒绝交出日记", "teen", "哈罗德向唐娜读日记却拒绝交付，唐娜转而请麦蒂协助偷取。", [("harold", "拒绝交出日记"), ("donna", "策划取回日记"), ("maddy", "同意协助"), ("laura", "日记内容被阅读")]),
    event(4, "audrey-ransom", "让以奥黛丽录像勒索本", "horne", "让要求本支付赎金并指定库珀交付，把家庭勒索与复仇计划合并。", [("jean", "提出赎金条件"), ("ben", "收到女儿被囚录像"), ("audrey", "继续作为人质"), ("cooper", "被指定送款")]),
    event(4, "josie-returns", "乔西回镇并遭乔纳森控制", "packard", "乔西声称从西雅图归来，却被所谓表亲乔纳森要求返回香港；乔纳森同时殴打汉克。", [("josie", "回到双峰镇"), ("pete", "欢迎乔西"), ("jonathan", "要求她回香港"), ("hank", "遭到威胁")]),
    event(4, "lucy-reveals-dick", "露西说明与迪克的关系", "town", "露西告诉安迪，迪克也可能是孩子父亲且曾劝她终止妊娠。", [("lucy", "公开另一段关系"), ("andy", "得知父亲竞争者"), ("dick", "成为父亲候选")]),
    event(4, "food-critic-rumor", "双 R 等待神秘美食评论家", "diner", "诺玛和汉克得知化名 M.T. Wentz 的评论家将到访，开始紧张准备。", [("norma", "期待餐厅评价"), ("hank", "协助经营并谋求生意")]),

    event(5, "sternwood-hearing", "斯特恩伍德法官处理利兰与利奥", "town", "法官准许利兰保释并认定利奥暂时不能受审，同时提醒库珀注意树林。", [("judge", "主持听证"), ("leland", "获准保释"), ("leo", "被认定无受审能力"), ("cooper", "收到树林提示"), ("lodwick", "代表起诉"), ("jack_racine", "为利奥提交脑活动证据")]),
    event(5, "robertson-house", "布伦斯顿夫妇否定罗伯逊地址", "laura-case", "鹰查到利兰所指房屋属于两名退休教师，他们从未听说 BOB 或罗伯逊。", [("hawk", "核查童年地址"), ("brunstons", "否认认识罗伯逊"), ("leland", "童年叙述产生疑点"), ("bob", "身份仍无法按普通人查证")]),
    event(5, "tojamura-bid", "“东村先生”竞购幽灵木", "packard", "化装后的凯瑟琳以日本投资者身份向本提出五百万美元交易。", [("catherine", "化装成东村先生"), ("ben", "收到幽灵木报价")]),
    event(5, "nadine-teen", "娜丁以高中生心态醒来", "diner", "娜丁从自杀未遂中醒来，认为自己仍是高中生，并显示异常力量。", [("nadine", "心智退回高中时期"), ("ed", "面对妻子认知改变"), ("jacoby", "负责心理照护")]),
    event(5, "oej-rescue", "突袭独眼杰克救出奥黛丽", "horne", "库珀、杜鲁门和鹰越境营救奥黛丽；布莱姬死亡，让·雷诺逃脱。", [("cooper", "领导越境营救"), ("truman", "协助突袭"), ("hawk", "提供武力支援"), ("audrey", "获救"), ("blackie", "行动中死亡"), ("jean", "逃离现场"), ("nancy", "参与抵抗")]),
    event(5, "diary-theft-fails", "唐娜与麦蒂偷日记失败", "teen", "两人试图从哈罗德家取走日记，被情绪崩溃的哈罗德当场抓住。", [("donna", "实施偷取"), ("maddy", "假扮劳拉分散注意"), ("harold", "发现背叛"), ("laura", "日记仍未取回")]),
    event(5, "andy-fertility", "安迪恢复生育能力并追去诊所", "town", "新检查证明安迪可能是父亲，他赶去阻止露西作出仓促决定。", [("andy", "确认可能是父亲"), ("lucy", "前往诊所"), ("dick", "仍是另一候选")]),

    event(6, "harold-rescue", "詹姆斯救出唐娜与麦蒂", "teen", "詹姆斯冲入哈罗德家救出两人，但劳拉日记仍留在原处。", [("james", "实施营救"), ("donna", "逃离哈罗德"), ("maddy", "逃离哈罗德"), ("harold", "与唐娜关系彻底破裂")]),
    event(6, "audrey-home", "奥黛丽回家并拒绝本的亲近", "horne", "库珀把严重摄入海洛因的奥黛丽送回本身边，她拒绝父亲的情感补偿。", [("cooper", "护送奥黛丽回家"), ("truman", "确认雷诺贩毒身份"), ("audrey", "拒绝父亲"), ("ben", "试图修复关系")]),
    event(6, "gordon-evidence", "戈登带来枪击与日记证据", "earle-fbi", "戈登说明枪手外套纤维、杰拉德药物和房外纸屑的新发现。", [("gordon", "汇总 FBI 证据"), ("cooper", "接收调查更新"), ("mike", "药物成为异常线索")]),
    event(6, "mike-reveals-bob", "MIKE 现身并说 BOB 藏在大北方", "lodge", "杰拉德停药后被 MIKE 控制，讲述与 BOB 的旧关系并指出其藏身酒店。", [("mike", "接管杰拉德并指认"), ("cooper", "审讯 MIKE"), ("truman", "见证附身"), ("bob", "被指向大北方酒店")]),
    event(6, "earle-chess-opening", "厄尔送来第一步棋", "earle-fbi", "戈登转交匿名国际象棋开局，库珀判断它来自温德姆·厄尔。", [("gordon", "转交匿名棋步"), ("cooper", "认出厄尔手法"), ("windom", "开启杀人棋局")]),
    event(6, "benefit-collapse", "利奥伤残补助远低于预期", "johnson", "雪莉和鲍比发现补助无法支撑计划，两人的护理骗局开始崩坏。", [("shelly", "承担护理负担"), ("bobby", "发现收益不足"), ("leo", "继续成为被护理者")]),

    event(7, "harold-death", "哈罗德死亡与日记重组", "teen", "鹰发现哈罗德上吊；被撕坏的日记重组成 BOB 长期虐待劳拉的证据。", [("hawk", "发现遗体"), ("harold", "自杀并留下法语短句"), ("donna", "承认日记线索"), ("laura", "日记揭示长期受害"), ("cooper", "获得关键证据")]),
    event(7, "ben-arrested", "奥黛丽揭露本与劳拉，本被捕", "laura-case", "奥黛丽逼父亲承认与劳拉发生关系，库珀和杜鲁门据此把本作为主要嫌疑人逮捕。", [("audrey", "揭露父亲秘密"), ("ben", "承认与劳拉关系并被捕"), ("laura", "旧关系成为嫌疑依据"), ("cooper", "执行调查判断"), ("truman", "执行逮捕")]),
    event(7, "maddy-murder", "利兰／BOB 杀害麦蒂", "laura-case", "麦蒂准备回家时，利兰给莎拉下药并在 BOB 控制下杀害麦蒂；莎拉看见白马异象。", [("leland", "在家中实施杀害"), ("bob", "占据利兰并杀人"), ("maddy", "成为第二名受害者"), ("sarah", "被下药并看见白马"), ("pale_horse", "作为死亡预兆出现")]),
    event(7, "roadhouse-warning", "巨人在酒吧宣告“又发生了”", "lodge", "木头女士把众人引向酒吧，巨人向库珀发出警告，镇上数人同时感到悲剧。", [("log_lady", "引导库珀到酒吧"), ("cooper", "看见巨人警告"), ("giant", "宣告悲剧重演"), ("waiter", "向库珀表达悲伤"), ("donna", "感到异常"), ("james", "感到异常"), ("bobby", "感到异常")]),
    event(7, "leo-tape", "鲍比发现利奥靴跟录音", "johnson", "鲍比在利奥靴跟找到秘密录音，为本参与锯木厂纵火提供证据。", [("bobby", "发现隐藏录音"), ("leo", "藏匿商业证据"), ("ben", "被录音指向纵火")]),

    event(8, "ben-defense", "杰里为错误嫌疑人本准备辩护", "horne", "杰里接手辩护，本提出凯瑟琳为不在场证人，但她仍被认为死于火灾。", [("ben", "坚持无罪"), ("jerry", "担任辩护人"), ("catherine", "成为失踪的不在场证人")]),
    event(8, "dead-girl-drive", "利兰携麦蒂尸体穿城", "laura-case", "利兰把尸体藏入高尔夫球袋，几乎在库珀和杜鲁门拦车时暴露。", [("leland", "运输并隐藏尸体"), ("maddy", "尸体被藏匿"), ("cooper", "临检时错过真相"), ("truman", "临检时错过真相"), ("bob", "在镜中显露")]),
    event(8, "mill-tape", "录音把本与锯木厂纵火相连", "packard", "鲍比确认利奥录音可用于勒索本，并改变雪莉与自己的计划。", [("bobby", "解读录音并筹划勒索"), ("leo", "留下录音"), ("ben", "被录音掌握")]),
    event(8, "tojamura-blackmail", "东村以不在场证明换幽灵木", "packard", "化装的凯瑟琳向本提供可洗清嫌疑的录音，交换幽灵木权益。", [("catherine", "以东村身份勒索"), ("ben", "用资产换取证词")]),
    event(8, "maddy-found", "麦蒂遗体被发现", "laura-case", "利兰把尸体弃在树林后，库珀与杜鲁门接到又一宗同型谋杀。", [("maddy", "遗体被发现"), ("cooper", "接手第二宗谋杀"), ("truman", "确认新受害者"), ("leland", "完成弃尸")]),
    event(8, "mt-wentz", "M.T. Wentz 审查双 R", "diner", "诺玛努力通过神秘评论家的审查，却尚不知道评论家正是母亲维维安。", [("norma", "接受匿名审查"), ("vivian", "以 M.T. Wentz 身份观察"), ("hank", "关心餐厅收益")]),

    event(9, "tremond-page", "第二位特里蒙德夫人交出日记残页", "laura-case", "唐娜、库珀和安迪发现原来的祖孙不存在；新住户交出记录红房间梦的日记页。", [("donna", "回访送餐地址"), ("cooper", "读取梦境记录"), ("andy", "参与核实住户"), ("mrs_tremond_second", "交出残页"), ("mrs_tremond", "身份被否定"), ("pierre", "法语短句成为线索"), ("laura", "记录与库珀相同的梦")]),
    event(9, "maddy-truth", "唐娜确认麦蒂已死，詹姆斯离镇", "teen", "麦蒂母亲来电与杜鲁门的谋杀消息使唐娜确认真相，詹姆斯因自责骑车离开。", [("donna", "确认麦蒂死亡"), ("leland", "试图阻止唐娜"), ("truman", "带来新谋杀消息"), ("james", "自责离镇"), ("maddy", "失踪事实被戳破")]),
    event(9, "roadhouse-reveal", "巨人归还戒指，库珀想起凶手", "lodge", "库珀把本、利兰、艾德和布里格斯带到酒吧；巨人与侍者出现，使他想起劳拉说“父亲杀了我”。", [("cooper", "恢复梦中记忆"), ("giant", "归还戒指"), ("waiter", "与巨人形象重合"), ("ben", "被用作诱饵"), ("leland", "被锁定"), ("ed", "参与诱捕"), ("garland", "参与诱捕"), ("laura", "梦中信息被忆起")]),
    event(9, "leland-death", "利兰被捕、BOB 离体并死亡", "laura-case", "库珀与杜鲁门拘捕利兰；BOB 迫使他自伤后离体，利兰在库珀怀中恢复记忆并死去。", [("cooper", "诱捕并安抚利兰"), ("truman", "协助拘捕"), ("leland", "坦白后死亡"), ("bob", "离开宿主体内"), ("laura", "谋杀真相被确认"), ("maddy", "谋杀真相被确认")]),
    event(9, "critic-reveal", "维维安承认自己是 M.T. Wentz", "diner", "诺玛得知母亲就是匿名评论家，而且给双 R 写下不利评价。", [("norma", "面对母亲背叛"), ("vivian", "承认评论家身份")]),

    event(10, "palmer-aftermath", "帕尔默家葬礼与真凶余波", "laura-case", "库珀向莎拉解释利兰受到黑暗力量控制；唐娜转述詹姆斯的自责。", [("cooper", "安慰莎拉并解释附身"), ("sarah", "面对丈夫与女儿死亡"), ("donna", "转述詹姆斯状态"), ("ed", "接收詹姆斯消息"), ("leland", "被安葬")]),
    event(10, "milford-wedding", "米尔福德兄弟因拉娜婚姻争执", "town", "镇长德韦恩反对弟弟道吉迎娶年轻的拉娜，兄弟公开冲突。", [("dwayne", "反对婚姻"), ("dougie", "迎娶拉娜"), ("lana", "进入米尔福德家")]),
    event(10, "nadine-school", "娜丁重返高中", "diner", "雅各比说服学校接纳心智停留在十八岁的娜丁。", [("nadine", "成为高中生"), ("jacoby", "促成入学"), ("ed", "继续照护妻子")]),
    event(10, "cooper-suspended", "库珀因越境突袭被停职", "earle-fbi", "罗杰·哈迪暂停库珀职务；金上尉称独眼杰克毒品失踪，DEA 调查启动。", [("roger", "宣布停职"), ("cooper", "失去 FBI 职务"), ("preston", "提出毒品指控"), ("truman", "支持库珀")]),
    event(10, "renault-frame", "让、厄尼与金筹划陷害库珀", "earle-fbi", "让让厄尼筹集毒品资金，金上尉计划把毒品栽入库珀车辆。", [("jean", "组织陷害"), ("ernie", "被要求销售毒品"), ("preston", "准备栽赃"), ("cooper", "成为目标")]),
    event(10, "briggs-vanishes", "布里格斯谈白色小屋后消失", "lodge", "露营时布里格斯向库珀提起白色小屋，强光出现后少校凭空失踪。", [("garland", "在强光中消失"), ("cooper", "目击失踪并寻找少校")]),
    event(10, "bobby-blackmail", "鲍比用利奥录音接近本", "johnson", "鲍比计划以锯木厂录音勒索本，为自己和雪莉取得资源。", [("bobby", "持录音接近本"), ("ben", "成为勒索对象"), ("shelly", "期待新生活"), ("leo", "录音来源")]),

    event(11, "denise-arrives", "丹尼斯抵达调查失踪毒品", "earle-fbi", "戈登通知后，DEA 特工丹尼斯·布莱森到镇调查库珀，仍以旧友身份尊重他。", [("gordon", "派出 DEA 调查"), ("denise", "接手案件"), ("cooper", "接受旧友调查")]),
    event(11, "james-meets-evelyn", "詹姆斯受雇为伊芙琳修车", "marsh", "离镇的詹姆斯遇到伊芙琳，并被雇去修理她丈夫的昂贵汽车。", [("james", "接受修车工作"), ("evelyn", "雇用并接近詹姆斯"), ("jeffrey", "车辆与婚姻成为背景"), ("malcolm", "以兄长身份观察")]),
    event(11, "nicky-mentoring", "安迪与迪克共同照看尼基", "town", "为争取露西认可，安迪和迪克参与孤儿尼基的陪伴计划。", [("andy", "成为临时照护者"), ("dick", "与安迪竞争表现"), ("nicky", "进入两人生活"), ("lucy", "观察父亲候选")]),
    event(11, "hawk-lodge-lore", "鹰解释白色与黑色小屋", "lodge", "鹰告诉库珀，进入白色小屋前必须面对黑色小屋和自己的影子。", [("hawk", "讲述本地传说"), ("cooper", "首次系统了解两座小屋")]),
    event(11, "packard-reveal", "乔西交代埃克哈特，安德鲁被揭示仍活着", "packard", "乔西向杜鲁门说明埃克哈特威胁；安德鲁实际上与凯瑟琳合谋，准备把乔西当诱饵。", [("josie", "承认香港过去"), ("truman", "听取乔西秘密"), ("eckhardt", "被指为控制者"), ("andrew", "显露仍活着"), ("catherine", "与安德鲁合谋")]),
    event(11, "earle-king", "厄尔寄来“国王必须死”", "earle-fbi", "厄尔的棋步和录音把库珀明确标记为棋局中的国王。", [("windom", "发出死亡威胁"), ("cooper", "收到棋局讯息")]),

    event(12, "ben-hires-bobby", "本雇鲍比监视汉克", "horne", "精神状态混乱的本让鲍比跟踪与让、厄尼合作的汉克。", [("ben", "雇用鲍比"), ("bobby", "跟踪汉克"), ("hank", "参与雷诺交易"), ("jean", "经营毒品计划"), ("ernie", "协助交易")]),
    event(12, "dead-dog-farm", "死狗农场与诱捕计划", "earle-fbi", "库珀在待售房屋发现轮胎痕和毒品；丹尼斯迫使厄尼协助诱捕让。", [("cooper", "发现毒品现场"), ("denise", "设计卧底诱捕"), ("ernie", "被迫当线人"), ("jean", "成为目标"), ("truman", "准备行动")]),
    event(12, "dougie-dies", "道吉新婚后猝死", "town", "道吉与拉娜结婚不久死于心脏病，德韦恩指责拉娜用性杀死弟弟。", [("dougie", "新婚后死亡"), ("lana", "被指为黑寡妇"), ("dwayne", "指控拉娜")]),
    event(12, "nadine-wrestling", "娜丁加入摔跤队并迷恋迈克", "diner", "温盖特教练发现娜丁的超常力量并让她击败迈克，她把青春期感情投向他。", [("buck", "招募娜丁入队"), ("nadine", "加入摔跤队"), ("mike_nelson", "被击败并成为迷恋对象")]),
    event(12, "nicky-case", "社工解释尼基的创伤背景", "town", "朱迪·斯温把尼基个案交给露西、安迪与迪克，并说明他的早期创伤。", [("judy_swain", "说明个案背景"), ("nicky", "接受陪伴计划"), ("lucy", "参与会谈"), ("andy", "承担照护"), ("dick", "承担照护")]),
    event(12, "briggs-security", "莱利上校确认少校失踪涉及国家安全", "lodge", "莱利说明深空信息来自双峰树林；布里格斯随后在自家客厅突然归来。", [("colonel_reilly", "说明机密背景"), ("cooper", "追问失踪原因"), ("garland", "神秘归来"), ("betty", "见证丈夫返回")]),
    event(12, "josie-maid", "凯瑟琳迫使乔西成为女佣", "packard", "凯瑟琳以交给埃克哈特相威胁，剥夺乔西地位并控制她。", [("catherine", "勒索并降服乔西"), ("josie", "被迫当女佣"), ("eckhardt", "作为威胁筹码")]),
    event(12, "marsh-abuse-story", "马尔科姆向詹姆斯讲述马什婚姻", "marsh", "马尔科姆声称杰弗里长期虐待伊芙琳，推动詹姆斯进一步介入。", [("malcolm", "编造兄长身份与虐待叙事"), ("james", "被引入婚姻冲突"), ("evelyn", "与詹姆斯继续接近"), ("jeffrey", "被描绘为施暴者")]),

    event(13, "briggs-scars", "布里格斯带伤回忆巨型猫头鹰", "lodge", "少校展示三角伤痕并说空军一直非正式寻找白色小屋，随后被军方带走。", [("garland", "讲述猫头鹰与灵魂体验"), ("cooper", "听取小屋信息"), ("colonel_reilly", "所属军方介入")]),
    event(13, "nicky-files", "迪克怀疑尼基带来厄运", "town", "汽车事故后，迪克拉安迪调查孤儿院档案，试图证明尼基是恶魔。", [("dick", "产生偏执怀疑"), ("andy", "协助调查"), ("nicky", "被错误怀疑")]),
    event(13, "ben-civil-war", "本陷入南北战争妄想", "horne", "本把自己当作罗伯特·李并在房间重演葛底斯堡，本家人和鲍比试图配合。", [("ben", "陷入李将军妄想"), ("jerry", "参与角色扮演"), ("bobby", "配合妄想"), ("jacoby", "尝试治疗"), ("johnny", "参与家庭场景")]),
    event(13, "evelyn-affair", "詹姆斯与伊芙琳发生关系", "marsh", "修车完成后两人越界，马尔科姆继续推动针对杰弗里的阴谋。", [("james", "与伊芙琳发生关系"), ("evelyn", "引诱詹姆斯"), ("malcolm", "在幕后操控"), ("jeffrey", "成为预定受害者")]),
    event(13, "renault-killed", "死狗农场诱捕失控，让·雷诺被击毙", "earle-fbi", "让识破诱捕并扣住库珀，丹尼斯分散其注意，库珀开枪结束对峙。", [("cooper", "被劫持后反击"), ("denise", "伪装并分散让"), ("truman", "参与突袭"), ("hawk", "参与突袭"), ("jean", "被库珀击毙"), ("ernie", "线人身份暴露")]),
    event(13, "earle-first-body", "停电、利奥苏醒与厄尔棋局尸体", "earle-fbi", "全镇停电，利奥醒来；厄尔把埃里克尸体放入警长办公室并指向棋盘。", [("leo", "从昏迷中醒来"), ("shelly", "发现丈夫苏醒"), ("cooper", "检查棋局尸体"), ("truman", "办公室成为现场"), ("hawk", "追查变电站火灾"), ("windom", "布置杀人棋局"), ("erik", "成为棋局受害者")]),

    event(14, "leo-attacks", "利奥持斧袭击雪莉后逃走", "johnson", "利奥逼近雪莉，鲍比及时分散注意，雪莉刺伤他后他逃入树林。", [("leo", "持斧攻击并逃走"), ("shelly", "反击刺伤丈夫"), ("bobby", "赶到救援")]),
    event(14, "caroline-story", "库珀讲述卡罗琳之死", "earle-fbi", "库珀向杜鲁门承认自己爱过受保护证人卡罗琳，并认为厄尔杀死了妻子。", [("cooper", "讲述失败保护与旧爱"), ("windom", "被认定杀害妻子"), ("caroline", "成为宿怨核心"), ("truman", "听取厄尔背景")]),
    event(14, "briggs-white-lodge", "布里格斯称自己去过白色小屋", "lodge", "仍神志不清的少校相信失踪期间被带到白色小屋。", [("garland", "描述白色小屋经历"), ("cooper", "记录少校陈述")]),
    event(14, "eckhardt-arrives", "埃克哈特抵达，乔纳森被杀", "packard", "埃克哈特来到双峰；乔纳森死在西雅图，库珀与杜鲁门开始怀疑乔西。", [("eckhardt", "抵达双峰"), ("jonathan", "被杀害"), ("josie", "成为嫌疑人"), ("cooper", "调查乔纳森之死"), ("truman", "开始怀疑爱人")]),
    event(14, "james-framed", "伊芙琳与马尔科姆栽赃詹姆斯", "marsh", "杰弗里死于车祸，伊芙琳承认自己和马尔科姆安排证据，把詹姆斯推成嫌疑人。", [("evelyn", "参与制造车祸与栽赃"), ("malcolm", "作为情人和共犯"), ("james", "成为替罪者"), ("jeffrey", "在车祸中死亡")]),
    event(14, "leo-meets-earle", "利奥逃入厄尔小屋", "earle-fbi", "受伤的利奥在树林遇见温德姆·厄尔，落入新的控制关系。", [("leo", "进入厄尔小屋"), ("windom", "接收并控制利奥")]),
    event(14, "nicky-cleared", "尼基被证明只是事故受害者", "town", "威尔和露西纠正安迪、迪克的偏见，说明尼基一生只是连续遭遇悲剧。", [("nicky", "洗清恶魔误解"), ("andy", "放弃怀疑"), ("dick", "被纠正"), ("will", "解释尼基情况"), ("lucy", "斥责两人")]),

    event(15, "marsh-resolution", "伊芙琳反杀马尔科姆", "marsh", "马尔科姆准备杀死詹姆斯时，伊芙琳承认真情并射杀马尔科姆；詹姆斯洗清嫌疑。", [("james", "躲避追捕并获救"), ("donna", "帮助证明清白"), ("evelyn", "射杀共犯"), ("malcolm", "试图灭口后死亡")]),
    event(15, "caroline-mask", "厄尔散播卡罗琳衣物并留下死亡面具", "earle-fbi", "阿尔伯特说明厄尔向全国寄出卡罗琳衣物；厄尔又把死亡面具和录音放到库珀床上。", [("albert", "汇报厄尔模式"), ("cooper", "收到直接威吓"), ("windom", "利用卡罗琳创伤"), ("caroline", "遗物被当作威胁")]),
    event(15, "leo-enslaved", "厄尔用电击项圈奴役利奥", "earle-fbi", "厄尔囚禁利奥，让他抄写一首将送给三名女子的诗。", [("windom", "安装电击项圈并命令抄诗"), ("leo", "成为被控制的仆从")]),
    event(15, "chess-stalemate", "皮特帮助库珀拖延杀人棋局", "earle-fbi", "库珀确认每丢一枚棋子就会有人死，邀请棋手皮特设计和棋。", [("cooper", "识别杀人规则"), ("truman", "协助防止下一案"), ("pete", "计算和棋策略"), ("windom", "维持棋局威胁")]),
    event(15, "ben-recovers", "众人改写内战结局让本恢复", "horne", "奥黛丽、杰里、鲍比与雅各比让格兰特向李投降，利用妄想把本带回现实。", [("ben", "从内战妄想恢复"), ("audrey", "参与治疗剧本"), ("jerry", "扮演历史角色"), ("bobby", "参与角色扮演"), ("jacoby", "设计心理治疗")]),
    event(15, "poem-fragments", "厄尔向雪莉、奥黛丽和唐娜送诗", "pageant", "伪装的厄尔分别送出同一首诗的碎片，开始筛选与库珀相连的女性。", [("windom", "伪装并投递诗句"), ("shelly", "收到一段诗"), ("audrey", "收到一段诗"), ("donna", "收到一段诗")]),
    event(15, "vicuña-fiber", "乔西外套纤维连接库珀枪击", "packard", "库珀秘密取样乔西外套，阿尔伯特确认与枪击现场的骆马呢纤维一致。", [("cooper", "秘密取得纤维"), ("albert", "完成法医比对"), ("josie", "被证据指向枪击"), ("truman", "仍未得知全部真相"), ("jonathan", "死亡案继续并查")]),

    event(16, "josie-ballistics", "弹道学确认乔西枪击库珀", "packard", "阿尔伯特提交弹道结果，也确认乔西杀死乔纳森；杜鲁门无意中听见。", [("albert", "提交弹道结论"), ("cooper", "确认枪手身份"), ("truman", "听见爱人真相"), ("josie", "被正式证实"), ("jonathan", "谋杀获得结论")]),
    event(16, "pine-weasel", "惠勒加入松貂抗议计划", "horne", "本请惠勒阻击凯瑟琳，奥黛丽和杰里把幽灵木开发包装为松貂栖息地争议。", [("ben", "组织商业反击"), ("wheeler", "接受本的邀请"), ("audrey", "策划环保抗议"), ("jerry", "参与方案"), ("catherine", "成为商业对手")]),
    event(16, "josie-forced-meeting", "凯瑟琳迫使乔西面对埃克哈特", "packard", "凯瑟琳安排会面，乔西明白自己可能被带回香港；安德鲁则公开警告埃克哈特。", [("catherine", "安排致命会面"), ("josie", "被迫赴约"), ("eckhardt", "等待乔西"), ("andrew", "现身警告旧敌")]),
    event(16, "roadhouse-poem", "三名女子在酒吧拼合厄尔诗句", "pageant", "雪莉、奥黛丽和唐娜按邀请相聚，伪装的厄尔在旁观察。", [("shelly", "带来诗句"), ("audrey", "带来诗句"), ("donna", "带来诗句"), ("windom", "伪装观察候选人")]),
    event(16, "josie-dies", "乔西射杀埃克哈特后神秘死亡", "packard", "库珀与杜鲁门包围房间；乔西开枪杀死埃克哈特，随即死去，BOB 和另一个地方的人出现。", [("josie", "射杀旧控制者后死亡"), ("eckhardt", "被乔西杀死"), ("truman", "亲历爱人死亡"), ("cooper", "看见超自然余波"), ("bob", "在房间中嘲笑"), ("arm", "在幻象中出现")]),

    event(17, "truman-grief", "杜鲁门沉溺乔西之死", "packard", "杜鲁门退出日常工作并酗酒，库珀和鹰暂时承担警长办公室职责。", [("truman", "陷入哀伤"), ("josie", "死亡成为创伤"), ("cooper", "接管工作"), ("hawk", "保护警长")]),
    event(17, "annie-arrives", "安妮来到双 R", "diner", "离开修道院的安妮投奔诺玛，在双 R 工作并首次吸引库珀注意。", [("annie", "来到双峰镇"), ("norma", "接纳妹妹"), ("cooper", "第一次见到安妮")]),
    event(17, "matching-scars", "木头女士与布里格斯伤痕相呼应", "lodge", "木头女士展示童年失踪后留下的相似伤痕，令库珀把两次事件联系起来。", [("log_lady", "展示旧伤"), ("garland", "伤痕成为对应证据"), ("cooper", "连接失踪经验")]),
    event(17, "earle-visits-donna", "厄尔伪装成旧同学拜访海沃德家", "earle-fbi", "厄尔冒充威尔已死的医学院同学给唐娜留下棋子，继续把威胁送到库珀身边。", [("windom", "伪装并留下棋子"), ("donna", "接待陌生访客"), ("will", "认出身份造假"), ("cooper", "收到新的棋局讯息")]),
    event(17, "fashion-show", "幽灵木时装秀被松貂破坏", "horne", "奥黛丽和迪克主持环保时装秀，凯瑟琳揭穿商业动机，逃脱的松貂令现场失控。", [("audrey", "组织时装秀"), ("dick", "担任主持"), ("ben", "推动停止开发运动"), ("catherine", "揭穿利益动机"), ("tim_pinkle", "参与活动执行")]),
    event(17, "puzzle-box-arrives", "琼斯把埃克哈特谜盒交给凯瑟琳", "packard", "埃克哈特死后，助手琼斯按遗命送出层层嵌套的谜盒。", [("jones", "送交谜盒"), ("catherine", "开始破解"), ("eckhardt", "通过遗物继续布局")]),
    event(17, "jones-enters", "琼斯潜入杜鲁门房间", "packard", "琼斯制服看守并进入杜鲁门床上，准备执行埃克哈特的报复。", [("jones", "潜入并准备袭击"), ("truman", "在悲痛中成为目标")]),

    event(18, "jones-attack", "琼斯试图勒死杜鲁门", "packard", "琼斯发动袭击但被杜鲁门制服；库珀判断动机来自埃克哈特的嫉妒。", [("jones", "实施勒杀"), ("truman", "反制袭击"), ("cooper", "解释报复动机"), ("eckhardt", "死后报复来源")]),
    event(18, "audrey-wheeler", "奥黛丽与惠勒开始恋情", "horne", "惠勒邀请奥黛丽乘私人飞机，两人的商业合作转向爱情。", [("audrey", "接受飞行邀请"), ("wheeler", "追求奥黛丽"), ("randy", "负责飞机行程")]),
    event(18, "bonsai-bug", "厄尔用盆栽窃听警长办公室", "earle-fbi", "厄尔冒充乔西送来盆栽并藏入监听器，开始直接监听库珀调查。", [("windom", "安装监听装置"), ("truman", "收下假礼物"), ("cooper", "在不知情下被窃听"), ("josie", "名字被用于伪装")]),
    event(18, "cooper-reinstated", "戈登恢复库珀职务并揭示蓝皮书联系", "earle-fbi", "戈登说明厄尔曾与布里格斯研究黑白小屋，并正式让库珀复职。", [("gordon", "恢复库珀 FBI 身份"), ("cooper", "复职并获得机密"), ("garland", "被连接到厄尔研究"), ("windom", "蓝皮书历史被揭开")]),
    event(18, "pageant-target", "厄尔决定杀死双峰小姐", "pageant", "厄尔告诉受控的利奥，下一名祭品将是选美冠军。", [("windom", "选定未来受害者"), ("leo", "被迫协助计划")]),
    event(18, "donna-follows-eileen", "唐娜跟踪艾琳去见本", "pageant", "艾琳与本秘密会面，唐娜开始怀疑两人关系与自己身世有关。", [("donna", "跟踪母亲"), ("eileen", "秘密会见旧情人"), ("ben", "与艾琳谈话")]),
    event(18, "owl-cave-symbol", "安妮认出布里格斯伤痕来自猫头鹰洞", "lodge", "安妮把伤痕认作洞穴岩画；库珀找到图案，厄尔随后进入洞中触发震动。", [("annie", "认出岩画"), ("garland", "伤痕提供图形"), ("log_lady", "相同伤痕强化线索"), ("cooper", "找到猫头鹰洞"), ("windom", "进入洞穴触发反应")]),
    event(18, "gordon-shelly", "戈登能听清雪莉并吻她", "diner", "戈登意外能听清雪莉的轻声说话并亲吻她，引发鲍比嫉妒。", [("gordon", "被雪莉吸引"), ("shelly", "与戈登亲吻"), ("bobby", "产生嫉妒")]),

    event(19, "owl-cave-visited", "库珀确认厄尔到过猫头鹰洞", "lodge", "库珀和杜鲁门检查洞穴痕迹，确定厄尔也在追索同一幅图。", [("cooper", "分析洞穴证据"), ("truman", "协助调查"), ("windom", "留下到访痕迹")]),
    event(19, "rusty-kidnapped", "厄尔向拉斯蒂讲述黑色小屋并将其杀害", "earle-fbi", "厄尔绑架巡演音乐家拉斯蒂，宣称要获取小屋力量，再把他装进巨大棋子射杀。", [("windom", "绑架并杀害"), ("rusty", "成为棋局祭品"), ("leo", "在胁迫下协助")]),
    event(19, "poem-handwriting", "库珀从笔迹确认利奥抄写诗句", "earle-fbi", "诗句笔迹与利奥被捕记录吻合，库珀明白利奥仍活着且受厄尔控制。", [("cooper", "完成笔迹比对"), ("leo", "被确认是抄写者"), ("windom", "通过利奥传信")]),
    event(19, "nested-box", "谜盒跌落后露出更小盒子", "packard", "皮特协助凯瑟琳破解谜盒，意外跌落让第一层开启。", [("catherine", "持有谜盒"), ("pete", "协助破解"), ("andrew", "关注埃克哈特遗产")]),
    event(19, "lana-rigging", "拉娜请求德韦恩操纵选美", "pageant", "拉娜与德韦恩交往，并说服身为评委的他确保自己获胜。", [("lana", "要求内定冠军"), ("dwayne", "同意操纵评审")]),
    event(19, "cooper-annie-past", "库珀与安妮谈及彼此创伤", "pageant", "库珀说出卡罗琳失败，安妮谈到自杀未遂和修道院，两人的关系加深。", [("cooper", "坦白卡罗琳创伤"), ("annie", "坦白自杀经历"), ("caroline", "作为库珀过去被提起")]),
    event(19, "gordon-kiss-fallout", "鲍比因戈登与雪莉冲突", "diner", "戈登再次向雪莉示好，鲍比公开表达嫉妒。", [("gordon", "追求雪莉"), ("shelly", "接受关注"), ("bobby", "不满戈登")]),
    event(19, "donna-questions-eileen", "唐娜追问艾琳与本的会面", "pageant", "艾琳声称会面只是慈善事务，唐娜仍不相信。", [("donna", "追问身世线索"), ("eileen", "否认旧情影响"), ("ben", "继续成为疑点")]),

    event(20, "earle-lodge-motive", "库珀识破厄尔真正目标是黑色小屋", "lodge", "布里格斯讲述追求纯粹邪恶的 dugpa，库珀把棋局与寻找小屋联系起来。", [("cooper", "推断厄尔目标"), ("garland", "提供 dugpa 信息"), ("windom", "从复仇转向夺取力量")]),
    event(20, "wheeler-leaves", "惠勒离镇，奥黛丽赶赴机场", "horne", "惠勒突然要去巴西；皮特送奥黛丽追到飞机，两人在机上告别。", [("wheeler", "因工作离镇"), ("audrey", "赶赴机场告别"), ("pete", "驾车帮助奥黛丽"), ("randy", "准备起飞")]),
    event(20, "donna-birth-certificate", "唐娜发现出生证明没有父亲姓名", "pageant", "出生证明强化唐娜对艾琳、本和威尔隐瞒事实的怀疑。", [("donna", "发现父亲栏空白"), ("eileen", "继续隐瞒旧情"), ("will", "养父身份受质疑"), ("ben", "可能生父嫌疑增强")]),
    event(20, "briggs-abducted", "厄尔绑架布里格斯并获得行星线索", "lodge", "厄尔麻醉少校，逼问后得知木星与土星相会时小屋会开启。", [("windom", "绑架并审讯"), ("garland", "泄露行星会合条件")]),
    event(20, "metal-cube", "安德鲁砸开第三层谜盒", "packard", "安德鲁用擀面杖砸开盒子，里面只剩一个金属立方体。", [("andrew", "暴力开启谜盒"), ("catherine", "继续追索遗产"), ("pete", "参与层层破解")]),
    event(20, "giant-says-no", "巨人在库珀与安妮共舞时警告", "lodge", "库珀和安妮在酒吧共舞，巨人挥手无声说“不”，预示关系将把她置于危险。", [("cooper", "与安妮共舞"), ("annie", "与库珀确认感情"), ("giant", "发出否定警告")]),
    event(20, "petroglyph-map", "厄尔与安迪分别看出岩画是地图", "lodge", "厄尔在囚禁处、安迪在警局同时识别出猫头鹰洞图的地图结构。", [("windom", "解读地图"), ("andy", "独立发现地图含义"), ("cooper", "接收安迪判断")]),
    event(20, "bob-returns", "BOB 在树林光幕中重现", "lodge", "黑色小屋接近开启时，BOB 从强光中出现，红房间帷幕映在其下。", [("bob", "在树林现身")]),
    event(20, "bobby-shelly-reconcile", "鲍比与雪莉重申感情", "johnson", "经历利奥与生活压力后，两人确认仍然相爱。", [("bobby", "向雪莉承诺"), ("shelly", "接受和解")]),

    event(21, "leo-frees-briggs", "利奥释放布里格斯并遭厄尔惩罚", "earle-fbi", "利奥请求少校救雪莉并放他逃走；厄尔把利奥留在悬挂狼蛛笼下。", [("leo", "释放少校并求救"), ("garland", "逃离厄尔控制"), ("windom", "用狼蛛机关惩罚利奥"), ("shelly", "成为利奥求救对象")]),
    event(21, "ghostwood-bank", "奥黛丽发现银行暗中资助幽灵木", "packard", "调查资金流时，奥黛丽把幽灵木开发与双峰储蓄贷款银行联系起来。", [("audrey", "查明银行融资"), ("ben", "抗议计划升级"), ("catherine", "开发项目受威胁")]),
    event(21, "fear-love-key", "恐惧、爱与行星会合成为开门条件", "lodge", "药物影响下的布里格斯说出爱与恐惧开启大门；库珀结合女王提示判断选美冠军是目标。", [("garland", "说出爱与恐惧"), ("cooper", "推断厄尔将绑架冠军"), ("windom", "等待天象开门"), ("bob", "被理解为吸食恐惧")]),
    event(21, "donna-father", "本承认可能是唐娜生父", "pageant", "唐娜逼问海沃德夫妇并在选美后台对质本；本承认与艾琳旧情和生父可能。", [("donna", "要求身世真相"), ("will", "拒绝回答"), ("eileen", "面对旧情"), ("ben", "承认可能为生父")]),
    event(21, "miss-twin-peaks", "安妮赢得双峰小姐", "pageant", "安妮、拉娜和雪莉等人参加选美；露西在活动中选择安迪，安妮最终夺冠。", [("annie", "赢得冠军"), ("lana", "参赛并试图内定"), ("shelly", "参赛"), ("dwayne", "担任被游说的评委"), ("tim_pinkle", "主持活动"), ("brock", "参与舞台活动"), ("lucy", "选择安迪"), ("andy", "被露西选择"), ("dick", "退出父亲竞争")]),
    event(21, "annie-kidnapped", "厄尔伪装成木头女士绑走安妮", "pageant", "厄尔切断灯光并释放烟雾，带走刚夺冠的安妮，库珀迟一步发现目标。", [("windom", "伪装并实施绑架"), ("annie", "被带往黑色小屋"), ("cooper", "发现爱人成为女王棋子"), ("log_lady", "身份被厄尔冒用")]),

    event(22, "enter-lodge", "厄尔带安妮入小屋，库珀追随", "lodge", "厄尔在树林中的红帷幕入口带安妮消失，库珀随后独自进入。", [("windom", "带祭品进入"), ("annie", "被挟持进入"), ("cooper", "追入黑色小屋")]),
    event(22, "lodge-trial", "红房间试炼与分身出现", "lodge", "库珀在红房间见到劳拉、麦蒂、利兰、卡罗琳、巨人和侍者，并遭多个分身追逐与欺骗。", [("cooper", "接受小屋试炼"), ("arm", "主持红房间阶段"), ("laura", "预告二十五年后再见"), ("maddy", "作为幻象出现"), ("leland", "作为幻象出现"), ("caroline", "被厄尔幻化利用"), ("giant", "在小屋中出现"), ("waiter", "与巨人同场转换"), ("laura_double", "攻击性显现"), ("leland_double", "在走廊出现"), ("arm_double", "分身出现"), ("caroline_double", "与安妮形象互换"), ("cooper_double", "追逐真正库珀")]),
    event(22, "earle-soul", "BOB 否定厄尔交易并夺走其灵魂", "lodge", "厄尔提出用安妮生命交换库珀灵魂，BOB 宣称他无权索取，转而夺走厄尔灵魂。", [("windom", "提出灵魂交易并被击败"), ("annie", "成为交易筹码"), ("cooper", "愿意牺牲自己"), ("bob", "夺走厄尔灵魂")]),
    event(22, "wrong-cooper", "库珀分身回到现实", "lodge", "安妮与外表像库珀的人获救；回到酒店后，分身撞向镜子，BOB 在倒影中出现。", [("cooper", "本体命运不明"), ("cooper_double", "占据现实位置"), ("annie", "获救但状态不明"), ("bob", "在镜中确认控制")]),
    event(22, "nadine-recovers", "娜丁头部受伤后恢复记忆", "diner", "选美混乱中的撞击让娜丁恢复真实年龄记忆，艾德、诺玛和迈克的关系重新洗牌。", [("nadine", "恢复婚姻记忆"), ("ed", "回到婚姻责任"), ("norma", "与艾德未来再度不确定"), ("mike_nelson", "失去高中恋人")]),
    event(22, "hayward-confrontation", "本试图修补海沃德家庭却被威尔击倒", "pageant", "本到海沃德家承担唐娜身世责任，西尔维娅赶来争执，威尔愤怒攻击本并令他撞伤头部。", [("ben", "试图承认并补救"), ("sylvia", "赶来与丈夫争执"), ("will", "攻击本"), ("eileen", "夹在旧情与家庭之间"), ("donna", "面对两位父亲")]),
    event(22, "bank-bomb", "谜盒钥匙引爆银行炸弹", "packard", "米布勒带安德鲁和皮特找到保险箱，钥匙触发埃克哈特炸弹；奥黛丽正锁在金库门前抗议幽灵木。", [("dell", "带众人找到保险箱并遭爆炸"), ("andrew", "开启保险箱并遭爆炸"), ("pete", "协助开箱并遭爆炸"), ("catherine", "继承线留下悬念"), ("audrey", "在金库前抗议并卷入爆炸"), ("eckhardt", "死后炸弹被触发")]),
    event(22, "sarah-message", "莎拉向布里格斯传递小屋讯息", "lodge", "莎拉以异常声音告诉布里格斯，自己在黑色小屋中与库珀一起等待他。", [("sarah", "成为讯息通道"), ("garland", "接收诡异讯息"), ("cooper", "被指仍在小屋中")]),
]


RELATIONSHIPS = [
    relation("cooper", "truman", "调查搭档", list(range(1, 23)), "库珀与杜鲁门贯穿第二季共同处理劳拉案、乔西案、厄尔案和小屋线。"),
    relation("truman", "hawk", "警长与副警长", list(range(1, 23)), "鹰是杜鲁门最可靠的副手之一。"),
    relation("truman", "andy", "警长与副警长", list(range(1, 23)), "安迪在杜鲁门指挥下参与警局调查。"),
    relation("truman", "lucy", "警长与接线员", list(range(1, 23)), "露西负责警局通讯与行政支持。"),
    relation("cooper", "albert", "FBI 调查伙伴", [1, 2, 3, 9, 15, 16], "阿尔伯特为库珀提供法医和行为证据。"),
    relation("cooper", "gordon", "下属与上司", [6, 7, 18, 19], "戈登监督库珀并最终恢复其职务。"),
    relation("cooper", "hawk", "调查伙伴", [1, 3, 5, 6, 7, 13, 17, 18, 19, 20, 21, 22], "鹰提供追踪、行动和小屋传统知识。"),
    relation("cooper", "denise", "旧友与联合作战", [11, 12, 13], "丹尼斯在调查库珀的同时协助他对付让·雷诺。"),
    relation("cooper", "roger", "被停职者与审查者", [10, 11, 12], "罗杰负责调查独眼杰克突袭并暂停库珀。", True),
    relation("cooper", "windom", "前搭档／宿敌", list(range(11, 23)), "厄尔把库珀当作棋局中的国王，并用卡罗琳与安妮进行复仇。"),
    relation("cooper", "caroline", "旧爱／保护失败", [14, 15, 19, 22], "库珀爱过受保护证人卡罗琳，并始终为她的死亡自责。"),
    relation("windom", "caroline", "丈夫／凶手", [14, 15, 22], "厄尔娶卡罗琳并被库珀认定为杀害她的人。", True),
    relation("cooper", "annie", "恋人", [17, 18, 19, 20, 21, 22], "两人的感情成为厄尔进入黑色小屋的利用点。"),
    relation("cooper", "giant", "线索给予者", [1, 2, 7, 9, 20, 22], "巨人在梦境和现实边缘持续引导或警告库珀。", True),
    relation("giant", "waiter", "形象对应", [1, 7, 9, 22], "两者在关键时刻互相转换或呼应，具体本体关系保持神秘。"),
    relation("leland", "bob", "宿主与附身者", [1, 2, 7, 8, 9], "BOB 借利兰实施暴力并在利兰死前离体。", True),
    relation("mike", "bob", "昔日杀戮伙伴／对立", [3, 6, 7, 9], "MIKE 声称自己曾与 BOB 一同杀戮，后切断关系并帮助追查。"),
    relation("donna", "james", "恋人", [1, 2, 3, 5, 6, 7, 8, 9, 15], "劳拉死亡后两人的关系受麦蒂、调查和詹姆斯离镇影响。"),
    relation("james", "maddy", "相互吸引", [1, 2, 3, 5, 6, 7, 8], "麦蒂与劳拉的相貌及詹姆斯的情感投射形成短暂吸引。"),
    relation("donna", "harold", "调查者与日记保管人", [2, 3, 4, 5, 6, 7], "唐娜先取得哈罗德信任，偷日记行动使关系破裂。"),
    relation("jacoby", "eolani", "夫妻", [3], "伊奥拉妮在雅各比康复期间陪伴他。"),
    relation("laura", "harold", "生前知己／日记托付", [2, 3, 4, 5, 6, 7], "劳拉生前把秘密日记交给哈罗德保管。"),
    relation("donna", "laura", "挚友／调查对象", list(range(1, 10)), "唐娜通过劳拉的关系、送餐路线和日记理解她的秘密生活。"),
    relation("ben", "audrey", "父女冲突与修复", [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22], "奥黛丽由反抗父亲逐渐转向帮助其康复和事业。"),
    relation("audrey", "cooper", "单向迷恋／信任", [1, 2, 3, 4, 5, 6, 7, 8, 10], "奥黛丽迷恋库珀，库珀保持界限但重视她的勇气与线索。"),
    relation("audrey", "wheeler", "恋人", [16, 17, 18, 19, 20], "两人因幽灵木事务相识并在惠勒离镇前相爱。"),
    relation("ben", "catherine", "商业同谋／对手", [1, 5, 8, 10, 11, 12, 16, 17, 18, 21, 22], "两人围绕锯木厂和幽灵木反复合作、欺骗与争夺。"),
    relation("ben", "bobby", "雇主与跑腿人", [10, 12, 13, 15], "本雇鲍比跟踪汉克，鲍比也掌握纵火录音。"),
    relation("jean", "blackie", "犯罪合作者", [3, 4, 5], "二人共同利用被囚的奥黛丽向本与库珀复仇。"),
    relation("jean", "ernie", "毒品交易伙伴", [10, 12, 13], "让要求厄尼筹资并参与死狗农场交易。"),
    relation("jean", "hank", "犯罪交易伙伴", [10, 11, 12, 13], "汉克在后半季与让合作。"),
    relation("bobby", "shelly", "恋人", [1, 2, 3, 5, 6, 7, 8, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], "两人在利奥威胁、保险骗局和生活压力下仍反复选择彼此。"),
    relation("leo", "shelly", "虐待型婚姻", [1, 2, 5, 6, 7, 8, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], "利奥长期控制和伤害雪莉。", True),
    relation("bobby", "leo", "敌对", [1, 2, 5, 6, 7, 8, 10, 13, 14, 15], "鲍比与利奥因雪莉、毒品和录音证据持续冲突。"),
    relation("norma", "ed", "长期恋人", [1, 2, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 21, 22], "两人的关系被各自婚姻和娜丁失忆反复打断。"),
    relation("nadine", "mike_nelson", "失忆期恋人", [11, 12, 13, 17, 18, 19, 21, 22], "娜丁认为自己是高中生时与迈克交往。"),
    relation("andy", "lucy", "恋人／孩子父亲候选", [1, 2, 3, 4, 5, 8, 9, 10, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22], "露西最终在双峰小姐活动中选择安迪。"),
    relation("lucy", "dick", "旧情／孩子父亲候选", [3, 4, 9, 10, 11, 12, 13, 14, 17, 19, 21], "露西与迪克的短暂关系造成父亲身份不确定。"),
    relation("andy", "dick", "竞争者／临时搭档", [3, 4, 9, 10, 11, 12, 13, 14, 17, 19, 21], "两人既争夺露西认可，也共同照看尼基。"),
    relation("truman", "josie", "恋人", [1, 4, 6, 10, 11, 12, 13, 15, 16, 17, 18], "杜鲁门爱乔西，在发现她的罪行与死亡后崩溃。"),
    relation("catherine", "josie", "家族与商业敌手", [1, 4, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17], "二人争夺锯木厂控制权，凯瑟琳后来用埃克哈特控制乔西。"),
    relation("josie", "eckhardt", "旧情／控制与恐惧", [11, 12, 14, 15, 16], "埃克哈特试图把乔西带回香港，乔西最终射杀他。"),
    relation("josie", "jonathan", "被监视者与执行者", [1, 2, 3, 4, 6, 14, 15, 16], "乔纳森为埃克哈特监视乔西，最终被她杀死。"),
    relation("evelyn", "james", "利用与短暂爱情", [11, 12, 13, 14, 15], "伊芙琳先利用詹姆斯，最后因真情反杀马尔科姆。"),
    relation("evelyn", "malcolm", "情人与共犯", [12, 13, 14, 15], "两人共同安排杰弗里死亡并栽赃詹姆斯。"),
    relation("dwayne", "lana", "迷恋／选美操纵", [14, 19, 20, 21], "道吉死后德韦恩迷恋拉娜，并答应帮助她获选。"),
    relation("garland", "windom", "蓝皮书旧研究关系", [18, 19, 20, 21, 22], "两人过去都与蓝皮书计划和小屋研究有关，厄尔后来绑架少校。"),
    relation("windom", "leo", "奴役者与俘虏", [14, 15, 16, 17, 18, 19, 20, 21], "厄尔以电击项圈控制利奥并让他协助杀人计划。", True),
    relation("donna", "ben", "疑似父女", [18, 19, 20, 21, 22], "本与艾琳旧情令唐娜的生父身份保持未决。"),
    relation("bob", "cooper_double", "控制／附身", [22], "终集镜中 BOB 表明库珀分身受其控制。", True),
]


FAMILY_RELATIONS = [
    family("palmer-marriage", "union", "marriage", [("leland", "partner"), ("sarah", "partner")], "利兰与莎拉的婚姻", "widowed", notes="利兰在 S2E9 死亡。"),
    family("palmer-parentage", "parentage", "biological", [("laura", "child"), ("leland", "parent"), ("sarah", "parent")], "劳拉的父母", "acknowledged", context="palmer-marriage"),
    family("laura-maddy-cousins", "kinship", "other", [("laura", "member"), ("maddy", "member")], "表姐妹", notes="麦蒂与劳拉是表姐妹，外貌高度相似。"),
    family("horne-marriage", "union", "marriage", [("ben", "partner"), ("sylvia", "partner")], "本与西尔维娅的婚姻", "active"),
    family("horne-children", "parentage", "biological", [("audrey", "child"), ("ben", "parent"), ("sylvia", "parent")], "奥黛丽的父母", "acknowledged", context="horne-marriage"),
    family("horne-johnny", "parentage", "biological", [("johnny", "child"), ("ben", "parent"), ("sylvia", "parent")], "约翰尼的父母", "acknowledged", context="horne-marriage"),
    family("horne-brothers", "kinship", "sibling", [("ben", "member"), ("jerry", "member")], "霍恩兄弟"),
    family("briggs-marriage", "union", "marriage", [("garland", "partner"), ("betty", "partner")], "布里格斯夫妇", "active"),
    family("briggs-parentage", "parentage", "biological", [("bobby", "child"), ("garland", "parent"), ("betty", "parent")], "鲍比的父母", "acknowledged", context="briggs-marriage"),
    family("hayward-marriage", "union", "marriage", [("will", "partner"), ("eileen", "partner")], "海沃德夫妇", "active"),
    family("donna-legal-parent", "parentage", "legal", [("donna", "child"), ("will", "parent")], "威尔是唐娜的养育父亲", "acknowledged", notes="第二季末生物学父亲问题出现，但威尔一直承担父亲角色。"),
    family("donna-biological-question", "parentage", "biological", [("donna", "child"), ("eileen", "parent"), ("ben", "parent")], "唐娜生父疑问", "disputed", "disputed", [21, 22], "本承认自己可能是唐娜生父，第二季内未得到最终证明。"),
    family("hayward-gersten", "parentage", "biological", [("gersten", "child"), ("will", "parent"), ("eileen", "parent")], "格斯滕的父母", "acknowledged", context="hayward-marriage"),
    family("hayward-harriet", "parentage", "biological", [("harriet", "child"), ("will", "parent"), ("eileen", "parent")], "哈丽特的父母", "acknowledged", context="hayward-marriage"),
    family("ed-nadine-marriage", "union", "marriage", [("ed", "partner"), ("nadine", "partner")], "艾德与娜丁的婚姻", "active", notes="娜丁失忆期间婚姻关系被暂时扭曲。"),
    family("ed-james", "kinship", "other", [("ed", "member"), ("james", "member")], "叔侄", notes="艾德是詹姆斯的叔叔和主要监护性亲属。"),
    family("jacoby-marriage", "union", "marriage", [("jacoby", "partner"), ("eolani", "partner")], "雅各比夫妇", "active"),
    family("norma-hank-marriage", "union", "marriage", [("norma", "partner"), ("hank", "partner")], "诺玛与汉克的婚姻", "separated", notes="法律婚姻仍在，但两人长期分居且关系敌对。"),
    family("norma-annie", "kinship", "half_sibling", [("norma", "member"), ("annie", "member")], "同母异父姐妹"),
    family("vivian-norma", "parentage", "biological", [("norma", "child"), ("vivian", "parent")], "维维安与诺玛", "acknowledged"),
    family("shelly-leo-marriage", "union", "marriage", [("shelly", "partner"), ("leo", "partner")], "雪莉与利奥的婚姻", "active", notes="关系具有持续的家庭暴力。"),
    family("bobby-shelly-partnership", "union", "partnership", [("bobby", "partner"), ("shelly", "partner")], "鲍比与雪莉", "active", episodes=[1, 2, 3, 5, 6, 7, 8, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]),
    family("ed-norma-partnership", "union", "affair", [("ed", "partner"), ("norma", "partner")], "艾德与诺玛的长期关系", "active", notes="两人都受既有婚姻约束。"),
    family("lucy-andy-partnership", "union", "partnership", [("lucy", "partner"), ("andy", "partner")], "露西选择安迪", "active", episodes=[21, 22]),
    family("packard-marriage", "union", "marriage", [("josie", "partner"), ("andrew", "partner")], "乔西与安德鲁的婚姻", "widowed", episodes=[11, 14, 16], notes="安德鲁曾伪造死亡；乔西在 S2E16 死亡。"),
    family("martell-marriage", "union", "marriage", [("catherine", "partner"), ("pete", "partner")], "凯瑟琳与皮特的婚姻", "active"),
    family("packard-siblings", "kinship", "sibling", [("andrew", "member"), ("catherine", "member")], "帕卡德兄妹"),
    family("milford-brothers", "kinship", "sibling", [("dwayne", "member"), ("dougie", "member")], "米尔福德兄弟"),
    family("dougie-lana-marriage", "union", "marriage", [("dougie", "partner"), ("lana", "partner")], "道吉与拉娜的婚姻", "widowed", episodes=[10, 11, 12], notes="道吉婚后不久在 S2E12 死亡。"),
    family("earle-marriage", "union", "marriage", [("windom", "partner"), ("caroline", "partner")], "温德姆与卡罗琳的婚姻", "widowed", notes="卡罗琳在第二季故事开始前已被杀害。"),
]


# Filled only with source-canonical entries that have no independent narrative
# function in the Season 2 graph. The builder fails on every undeclared gap.
AUDIT_EXCLUSIONS = {
    "Black Lodge performer": "终集红房间中的无名表演者，仅承担氛围功能。",
    "Bob (Twin Peaks Sheriff's Department)": "警局背景副警长，且姓名会与超自然实体 BOB 混淆。",
    "Cappy": "酒吧背景人员，没有独立剧情因果。",
    "Carl": "单场景背景镇民，没有独立剧情因果。",
    "Clarence Brocklehurst": "本·霍恩内战妄想中的角色扮演者，不形成独立剧情线。",
    "Cop": "无名警员。",
    "Cyril Pons": "电视新闻画面中的记者，功能已由火灾事件节点承载。",
    "Daisy Packard": "仅以照片出现的帕卡德家族先人。",
    "Einar Thorson": "电话声音中的冰岛商业联系人，无独立剧情行动。",
    "Greege": "单场景背景人物。",
    "Harry S. Truman (president)": "现实历史人物，与同名警长无叙事关系。",
    "Heidi": "双 R 服务员的环境性出场。",
    "Irene Littlehorse": "单场景房地产／事务人员，死狗农场功能由事件节点承载。",
    "J.J. Horne": "霍恩家先人或画像性出现，不参与第二季行动。",
    "Jeff Moore (bellman)": "无独立剧情功能的酒店服务人员。",
    "Jeff Moore (deputy)": "无独立剧情功能的背景副警长。",
    "Joey Paulson": "单场景镇民／酒吧背景人物。",
    "Julee Cruise (fictional)": "酒吧舞台歌手，承担音乐氛围而非剧情行动。",
    "Louie Budway": "酒店背景职员，无独立剧情因果。",
    "Louis Armstrong": "现实音乐家，仅作文化性画面／声音引用。",
    "Louise Dombrowski": "轶事性背景人物，没有第二季行动线。",
    "Roadie": "无名巡演工作人员。",
    "Samantha": "单场景背景人物。",
    "Sid": "独眼杰克背景工作人员。",
    "Sleeping clerk": "终集无名值班职员。",
    "Susan": "单场景背景人物。",
    "Toad": "双 R 背景员工，没有独立剧情线。",
    "Tom Brockman": "电视节目主持人，承担环境信息功能。",
    "Zipper": "一次性背景角色／表演性称呼，无独立剧情因果。",
}
